# ----- marine battle setting config -----

# get env information
env: "sc2"
# get task information
task: "toy2"
# define train tasks and test tasks
train_tasks: ["3m", "5m", "10m"]
train_tasks_data_quality: {
    "3m": "medium",
    "5m": "medium",
    "10m": "medium",
}

test_tasks: ["3m", "4m", "5m", "7m", "10m", "12m"]
test_tasks_data_quality: {
}

# define additional pretrain tasks
pretrain_tasks: ["3m", "5m", "10m"]
pretrain_tasks_data_quality: {
    "3m": "medium",
    "5m": "medium",
    "10m": "medium",
}
